---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
data:
  server-tokens: 'false'
  http-snippet: |
      server {
        listen 18080;

        location /nginx_status {
          stub_status on;
        }

        location / {
          return 404;
        }
      }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
