---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
data:
  location-snippet: |
    location ~ robots.txt {
      add_header  Content-Type  text/plain;
      return 200 "User-agent: *\nDisallow: /\n";
    }
    add_header  X-Robots-Tag "noindex, nofollow";
