apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/tier: frontend
    spec:
      containers:
        - name: app
          image: image:staging
          imagePullPolicy: Always
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE
              value: craklabel/frontend-cfa-ilc
            - name: DD_LOGS_INJECTION
              value: 'false'
            - name: DD_TRACE_SAMPLE_RATE
              value: '1'
            - name: DD_PROFILING_ENABLED
              value: 'true'
          envFrom:
            - configMapRef:
                name: config
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 125Mi

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app.kubernetes.io/tier: frontend
  ports:
    - port: 80
      targetPort: 8233
      protocol: TCP
      name: http
